# Generated by Django 5.0.6 on 2026-05-28 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='normalizedrecord',
            new_name='ingestion_n_company_5c59b4_idx',
            old_name='ingestion_n_company_841d3d_idx',
        ),
        migrations.RenameIndex(
            model_name='normalizedrecord',
            new_name='ingestion_n_company_6b3bb2_idx',
            old_name='ingestion_n_company_bbf558_idx',
        ),
        migrations.RenameIndex(
            model_name='normalizedrecord',
            new_name='ingestion_n_activit_ef9478_idx',
            old_name='ingestion_n_activit_0adaeb_idx',
        ),
        migrations.RenameIndex(
            model_name='validationissue',
            new_name='ingestion_v_company_a7c2a2_idx',
            old_name='ingestion_v_company_dfa938_idx',
        ),
    ]
