# Generated by Django 5.0.6 on 2026-05-28 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_rename_ingestion_n_company_841d3d_idx_ingestion_n_company_5c59b4_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SapGoodsMovementStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant_code', models.CharField(blank=True, max_length=40)),
                ('posting_date', models.CharField(blank=True, max_length=40)),
                ('quantity', models.CharField(blank=True, max_length=40)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('material_description', models.CharField(blank=True, max_length=255)),
                ('source_document', models.CharField(blank=True, max_length=255)),
                ('vendor_name', models.CharField(blank=True, max_length=255)),
                ('raw_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sap_staging', to='ingestion.rawrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TravelExpenseStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_id', models.CharField(blank=True, max_length=80)),
                ('expense_type', models.CharField(blank=True, max_length=80)),
                ('transaction_date', models.CharField(blank=True, max_length=40)),
                ('amount', models.CharField(blank=True, max_length=40)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('vendor_name', models.CharField(blank=True, max_length=255)),
                ('origin_airport', models.CharField(blank=True, max_length=10)),
                ('destination_airport', models.CharField(blank=True, max_length=10)),
                ('distance_km', models.CharField(blank=True, max_length=40)),
                ('hotel_nights', models.CharField(blank=True, max_length=40)),
                ('raw_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travel_staging', to='ingestion.rawrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UtilityIntervalStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meter_id', models.CharField(blank=True, max_length=80)),
                ('period_start', models.CharField(blank=True, max_length=40)),
                ('period_end', models.CharField(blank=True, max_length=40)),
                ('usage', models.CharField(blank=True, max_length=40)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('source_document', models.CharField(blank=True, max_length=255)),
                ('tariff_description', models.CharField(blank=True, max_length=255)),
                ('raw_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='utility_staging', to='ingestion.rawrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
